# Generated by Django 5.0.4 on 2024-04-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='qr_code',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='宠物身份证二维码'),
        ),
    ]
