# Generated by Django 5.0.4 on 2024-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='qr_code',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='宠物身份证二维码'),
            preserve_default=False,
        ),
    ]
