# Generated by Django 5.0.4 on 2024-05-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(default='2024-04-02', verbose_name='出生日期'),
            preserve_default=False,
        ),
    ]
