# Generated by Django 5.0.4 on 2024-05-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_remove_pet_age_pet_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pet_avatars/', verbose_name='宠物头像'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sterilization',
            field=models.CharField(choices=[('未绝育', '未绝育'), ('已绝育', '已绝育'), ('未知', '未知')], default='未知', max_length=50, verbose_name='绝育情况'),
        ),
    ]
