# Generated by Django 5.0.4 on 2024-05-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_avatar_pet_sterilization'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_encyclopedia',
            name='species_name_cn',
            field=models.CharField(default=0, max_length=255, verbose_name='品种中文名'),
            preserve_default=False,
        ),
    ]
