# Generated by Django 5.0.4 on 2024-05-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_encyclopedia_species_name_cn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_encyclopedia',
            name='care_instruction',
            field=models.TextField(blank=True, null=True, verbose_name='护理建议'),
        ),
        migrations.AlterField(
            model_name='pet_encyclopedia',
            name='characteristic',
            field=models.TextField(blank=True, null=True, verbose_name='特征'),
        ),
    ]
