# Generated by Django 5.0.4 on 2024-05-21 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_pet_encyclopedia_species_name_cn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='species_id',
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pets.pet_encyclopedia', verbose_name='品种'),
            preserve_default=False,
        ),
    ]
