# Generated by Django 5.0.4 on 2024-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_remove_pet_species_id_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='宠物身份证二维码'),
        ),
    ]
