# Generated by Django 5.0.4 on 2024-05-22 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_alter_pet_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_care_diary',
            name='diary_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='日记日期'),
            preserve_default=False,
        ),
    ]
