# Generated by Django 5.0.4 on 2024-05-09 20:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='help',
            name='provider',
        ),
        migrations.AddField(
            model_name='help',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='help',
            name='title',
            field=models.CharField(default='标题', max_length=255, verbose_name='互助标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='help',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='HelpApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0, verbose_name='申请状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='help.help', verbose_name='互助信息')),
            ],
        ),
        migrations.CreateModel(
            name='HelpReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('help', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='help.help', verbose_name='互助信息')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='被评价者')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_made', to=settings.AUTH_USER_MODEL, verbose_name='评价者')),
            ],
        ),
    ]
