# Generated by Django 5.0.4 on 2024-04-20 00:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_alter_user_address_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('helpId', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0, verbose_name='互助状态')),
                ('detail', models.TextField(verbose_name='互助详情')),
                ('cost', models.CharField(max_length=255, verbose_name='佣金')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petId', models.AutoField(primary_key=True, serialize=False)),
                ('petName', models.CharField(max_length=50, verbose_name='宠物名字')),
                ('petType', models.IntegerField(verbose_name='类别')),
                ('speciesId', models.IntegerField(verbose_name='品种')),
                ('sex', models.IntegerField(verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('weight', models.FloatField(verbose_name='体重')),
                ('qrCode', models.CharField(max_length=255, unique=True, verbose_name='宠物身份证二维码')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('pictureUrl', models.JSONField(blank=True, null=True, verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollows',
            fields=[
                ('followId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='User',
        ),
        migrations.DeleteModel(
            name='PetFriendship',
        ),
        migrations.RemoveField(
            model_name='petprofile',
            name='User',
        ),
        migrations.RemoveField(
            model_name='walkservice',
            name='Pet',
        ),
        migrations.RemoveField(
            model_name='petcarediary',
            name='Pet',
        ),
        migrations.DeleteModel(
            name='UserFriendship',
        ),
        migrations.RemoveField(
            model_name='walkservice',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='walkservice',
            name='requester',
        ),
        migrations.AlterModelOptions(
            name='Notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='petcarediary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='petencyclopedia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='User',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usermessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='Notification',
            name='User',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='Notification',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.User',
                                    verbose_name='接收用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='receiver_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='received_messages', to='app.User', verbose_name='接收者ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='sender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='sent_messages', to='app.User', verbose_name='发送者ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='Notification',
            name='message',
            field=models.TextField(verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='petcarediary',
            name='content',
            field=models.TextField(verbose_name='日记内容'),
        ),
        migrations.AlterField(
            model_name='petcarediary',
            name='weight',
            field=models.FloatField(verbose_name='宠物体重'),
        ),
        migrations.AlterField(
            model_name='petencyclopedia',
            name='careInstruction',
            field=models.TextField(verbose_name='护理建议'),
        ),
        migrations.AlterField(
            model_name='petencyclopedia',
            name='characteristic',
            field=models.TextField(verbose_name='特征'),
        ),
        migrations.AlterField(
            model_name='petencyclopedia',
            name='petType',
            field=models.IntegerField(verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='petencyclopedia',
            name='speciesName',
            field=models.CharField(max_length=255, verbose_name='品种名'),
        ),
        migrations.AlterField(
            model_name='User',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='地址'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='User',
            name='avatar',
            field=models.CharField(max_length=200, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='User',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='账户创建日期'),
        ),
        migrations.AlterField(
            model_name='User',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='User',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='User',
            name='passwordHash',
            field=models.CharField(max_length=128, verbose_name='密码散列值'),
        ),
        migrations.AlterField(
            model_name='User',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=15, unique=True, verbose_name='电话号码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='messageContent',
            field=models.TextField(verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间'),
        ),
        migrations.AddField(
            model_name='help',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_provided',
                                    to='app.User', verbose_name='提供帮助的用户'),
        ),
        migrations.AddField(
            model_name='help',
            name='requester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests',
                                    to='app.User', verbose_name='发布互助的用户'),
        ),
        migrations.AddField(
            model_name='Pet',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User',
                                    verbose_name='关联的用户ID'),
        ),
        migrations.AddField(
            model_name='help',
            name='pet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pet',
                                    verbose_name='需要帮助的宠物ID'),
        ),
        migrations.AddField(
            model_name='petcarediary',
            name='petId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Pet',
                                    verbose_name='关联的宠物ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='发布人'),
        ),
        migrations.AddField(
            model_name='userfollows',
            name='followeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers',
                                    to='app.User', verbose_name='被关注者ID'),
        ),
        migrations.AddField(
            model_name='userfollows',
            name='followerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following',
                                    to='app.User', verbose_name='关注者ID'),
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='PetProfile',
        ),
        migrations.DeleteModel(
            name='WalkService',
        ),
    ]
