# Generated by Django 5.0.4 on 2024-04-20 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_help_pet_post_userfollows_remove_forum_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userId',
        ),
        migrations.AddField(
            model_name='help',
            name='tags',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.User',
                                    verbose_name='用户ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pictureUrl',
            field=models.JSONField(blank=True, null=True, verbose_name='图片URL'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='replies', to='app.comment', verbose_name='父评论ID')),
                ('post',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.post',
                                   verbose_name='帖子ID')),
                ('User',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户ID')),
            ],
        ),
    ]
