# Generated by Django 5.0.4 on 2024-04-23 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0005_rename_petcarediary_pet_care_diary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post',
                                   verbose_name='帖子ID')),
                ('User',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('User', 'post'), name='unique_like_post'),
        ),
    ]
