# Generated by Django 5.0.4 on 2024-04-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_like_post_remove_like_user_remove_post_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='Pet',
            new_name='pet',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pet_care_diary',
            old_name='Pet',
            new_name='pet',
        ),
    ]
