# Generated by Django 5.0.4 on 2024-04-24 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('app', '0008_remove_like_post_remove_like_user_remove_post_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('picture_url', models.JSONField(blank=True, null=True, verbose_name='图片URL')),
                ('tags', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='帖子创建时间')),
                ('User',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='点赞创建时间')),
                ('User',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户ID')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to='community.post', verbose_name='帖子ID')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='replies', to='community.comment', verbose_name='父评论ID')),
                ('User',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='用户ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                           to='community.post', verbose_name='帖子ID')),
            ],
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('User', 'post'), name='unique_like_post'),
        ),
    ]
